spring.application.name=Abaca-Ecommerce

server.port=5050
spring.datasource.url=jdbc:postgresql://localhost:5432/abaca_ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update